import breakpoints from './src/theme/breakpoints';
import { FILTER_DRAWER_WIDTH, HEADER, NAVBAR } from './src/utils/config';

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  important: '#__next',

  corePlugins: {
    preflight: false,
  },
  darkMode: 'selector',
  theme: {
    screens: {
      xs: `${breakpoints.xs}px`,
      sm: `${breakpoints.sm}px`,
      md: `${breakpoints.md}px`,
      lg: `${breakpoints.lg}px`,
      xl: `${breakpoints.xl}px`,
      xxl: `${breakpoints.xxl}px`,
    },
    colors: {
      transparent: 'transparent',
      inherit: 'inherit',
      overlay: '#04002121',
      grey: {
        0: 'var(--mui-palette-grey-0)',
        100: 'var(--mui-palette-grey-100)',
        200: 'var(--mui-palette-grey-200)',
        300: 'var(--mui-palette-grey-300)',
        400: 'var(--mui-palette-grey-400)',
        500: 'var(--mui-palette-grey-500)',
        600: 'var(--mui-palette-grey-600)',
        700: 'var(--mui-palette-grey-700)',
        800: 'var(--mui-palette-grey-800)',
        900: 'var(--mui-palette-grey-900)',
        500_8: 'var(--mui-palette-grey-5008)',
        500_12: 'var(--mui-palette-grey-50012)',
        500_16: 'var(--mui-palette-grey-50016)',
        500_24: 'var(--mui-palette-grey-50024)',
        500_32: 'var(--mui-palette-grey-50032)',
        500_48: 'var(--mui-palette-grey-50048)',
        500_56: 'var(--mui-palette-grey-50056)',
        500_80: 'var(--mui-palette-grey-50080)',
      },
      common: {
        black: 'var(--mui-palette-common-black)',
        white: 'var(--mui-palette-common-white)',
        divider: 'var(--mui-palette-divider)',
      },
      primary: {
        alpha: 'rgb(255, 251, 238)',
        lighter: 'var(--mui-palette-primary-lighter)',
        light: 'var(--mui-palette-primary-light)',
        main: 'var(--mui-palette-primary-main)',
        dark: 'var(--mui-palette-primary-dark)',
        darker: 'var(--mui-palette-primary-darker)',
        contrastText: 'var(--mui-palette-primary-contrastText)',
      },
      secondary: {
        alpha: 'rgba(102, 57, 255, 0.1)',
        lighter: 'var(--mui-palette-secondary-lighter)',
        light: 'var(--mui-palette-secondary-light)',
        main: 'var(--mui-palette-secondary-main)',
        dark: 'var(--mui-palette-secondary-dark)',
        darker: 'var(--mui-palette-secondary-darker)',
        contrastText: 'var(--mui-palette-secondary-contrastText)',
      },
      success: {
        lighter: 'var(--mui-palette-success-lighter)',
        light: 'var(--mui-palette-success-light)',
        main: 'var(--mui-palette-success-main)',
        dark: 'var(--mui-palette-success-dark)',
        darker: 'var(--mui-palette-success-darker)',
        contrastText: 'var(--mui-palette-success-contrastText)',
      },
      info: {
        lighter: 'var(--mui-palette-info-lighter)',
        light: 'var(--mui-palette-info-light)',
        main: 'var(--mui-palette-info-main)',
        dark: 'var(--mui-palette-info-dark)',
        darker: 'var(--mui-palette-info-darker)',
        contrastText: 'var(--mui-palette-info-contrastText)',
      },
      warning: {
        lighter: 'var(--mui-palette-warning-lighter)',
        light: 'var(--mui-palette-warning-light)',
        main: 'var(--mui-palette-warning-main)',
        dark: 'var(--mui-palette-warning-dark)',
        darker: 'var(--mui-palette-warning-darker)',
        contrastText: 'var(--mui-palette-warning-contrastText)',
      },
      error: {
        lighter: 'var(--mui-palette-error-lighter)',
        light: 'var(--mui-palette-error-light)',
        main: 'var(--mui-palette-error-main)',
        dark: 'var(--mui-palette-error-dark)',
        darker: 'var(--mui-palette-error-darker)',
        contrastText: 'var(--mui-palette-error-contrastText)',
      },
      background: {
        default: 'var(--mui-palette-background-default)',
        paper: 'var(--mui-palette-background-paper)',
      },
      text: {
        primary: 'var(--mui-palette-text-primary)',
        secondary: 'var(--mui-palette-text-secondary)',
        disabled: 'var(--mui-palette-text-disabled)',
      },
      action: {
        hover: 'var(--mui-palette-grey-50012)',
        selected: 'var(--mui-palette-action-selected)',
        disabled: 'var(--mui-palette-grey-50080)',
        disabledBackground: 'var(--mui-palette-grey-50024)',
        focus: 'var(--mui-palette-grey-50024)',
      },
      custom: {
        0: 'var(--mui-palette-custom-0)',
        1: 'var(--mui-palette-custom-1)',
        2: 'var(--mui-palette-custom-2)',
        3: 'var(--mui-palette-custom-3)',
        4: 'var(--mui-palette-custom-4)',
        5: 'var(--mui-palette-custom-5)',
        6: 'var(--mui-palette-custom-6)',
        7: 'var(--mui-palette-custom-7)',
        8: 'var(--mui-palette-custom-8)',
        9: 'var(--mui-palette-custom-9)',
        10: 'var(--mui-palette-custom-10)',
        11: 'var(--mui-palette-custom-11)',
        customGreen: 'var(--mui-palette-custom-customGreen)',
        customLightGreen: 'var(--mui-palette-custom-customLightGreen)',
      },
    },
    extend: {
      fontFamily: {
        yekan_bakh: 'Yekan_Bakh',
      },
      fontSize: {
        body1: '0.9375rem',
      },
      backgroundImage: {
        overlay_0: 'none',
        overlay_1:
          'linear-gradient(rgba(255 255 255 / 0.051), rgba(255 255 255 / 0.051))',
        widget: 'var(--mui-palette-gradients-widget)',
        price: 'linear-gradient(-90deg, #fff2d9 0%, transparent 100%)',
        cardProduct: 'linear-gradient(90deg, #6EE2E0 0%, #5257E5 100%)',
      },
      height: {
        header: HEADER.DESKTOP_HEIGHT,
        'header-offset': HEADER.DESKTOP_OFFSET_HEIGHT,
        'header-mobile': HEADER.MOBILE_HEIGHT,
        'header-profile': HEADER.PROFILE_HEIGHT,
        'header-full': HEADER.DESKTOP_FULL_HEIGHT,
        'header-mobile-full': HEADER.MOBILE_FULL_HEIGHT,
        navbar: NAVBAR.HEIGHT,
        'navbar-mobile': NAVBAR.MOBILE_HEIGHT,
        'mobile-app-bar': NAVBAR.MOBILE_APP_BAR_HEIGHT,
      },
      width: {
        'navbar-profile': `calc(100% - ${NAVBAR.PROFILE_WIDTH}px)`,
        'navbar-drawer': NAVBAR.DRAWER_WIDTH,
        'filter-drawer': FILTER_DRAWER_WIDTH,
      },
      margin: {
        header: HEADER.DESKTOP_FULL_HEIGHT,
        'header-mobile': HEADER.MOBILE_FULL_HEIGHT,
        'mobile-app-bar': NAVBAR.MOBILE_APP_BAR_HEIGHT,
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.625rem',
        90: '90px',
      },
      boxShadow: {
        s0: 'var(--mui-customShadows-s0)',
        s1: 'var(--mui-customShadows-s1)',
        s2: 'var(--mui-customShadows-s2)',
        s3: 'var(--mui-customShadows-s3)',
        s4: 'var(--mui-customShadows-s4)',
        s5: 'var(--mui-customShadows-s5)',
        s6: 'var(--mui-customShadows-s6)',
        s7: 'var(--mui-customShadows-s7)',
        s8: 'var(--mui-customShadows-s8)',
        s9: 'var(--mui-customShadows-s9)',
        s10: 'var(--mui-customShadows-s10)',
        s11: 'var(--mui-customShadows-s11)',
        s12: 'var(--mui-customShadows-s12)',
        s13: 'var(--mui-customShadows-s13)',
        s14: 'var(--mui-customShadows-s14)',
        s15: 'var(--mui-customShadows-s15)',
        s16: 'var(--mui-customShadows-s16)',
        s17: 'var(--mui-customShadows-s17)',
        s18: 'var(--mui-customShadows-s18)',
        primary: 'var(--mui-customShadows-primary)',
        info: 'var(--mui-customShadows-info)',
        secondary: 'var(--mui-customShadows-secondary)',
        success: 'var(--mui-customShadows-success)',
        warning: 'var(--mui-customShadows-warning)',
        customGreen: 'var(--mui-customShadows-customGreen)',
        customLightGreen: 'var(--mui-customShadows-customLightGreen)',
        error: 'var(--mui-customShadows-error)',
        card: 'var(--mui-customShadows-card)',
        dialog: 'var(--mui-customShadows-dialog)',
        dropdown: 'var(--mui-customShadows-dropdown)',
        contentCard: 'var(--mui-customShadows-contentCard)',
        roundedBox: 'var(--mui-customShadows-roundedBox)',
        customGreen:"var(--mui-customShadows-customGreen)",
        customLightGreen:"var(--mui-customShadows-customLightGreen)"
      },
    },
  },
  plugins: [
    function ({ addVariant }) {
      addVariant(`child`, `&>*`);
    },
    require('tailwind-scrollbar')({
      nocompatible: true,
      preferredStrategy: 'pseudoelements',
    }),
  ],
};
